# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: build -t dzmi3y/tableweather 
    - script: login -u dzmi3y -p 666ybprjehjdytdsqbyntkktrn666
    - script: push dzmi3y/tableweather 
   