steps:
    - script: |
        docker build -t $(dockerId)/$(imageName)  
        docker login -u $(dockerId) -p $(passwordDocker)
        docker push dzmi3y/tableweather 
        docker login --username=_ --password=$(token) registry.heroku.com
        docker build -t registry.heroku.com/apps/tableweather
        docker push registry.heroku.com/apps/tableweather	